prevent flaky tests by avoiding scanning the entire repo
Now that cli integration tests are running for Scala 3 since 18f6525,
parallelism increased and exposed a race condition between classpath
scanning in test execution and compilation of other unrelated modules
of the build.

(1)

```
ScalafixArgumentsSuite:
- evaluate sees a single patch for atomic patches *** FAILED *** (299 milliseconds)
  java.nio.file.NoSuchFileException:.../scalafix-tests/expect/target/jvm-2.13.14-target2.13.14xsource3/test-classes.bak
```

Targeting a specific source directory will avoid capturing class files,
and is enough for the SyntacticRule tested in ScalafixArgumentsSuite.

(2)

```
ScalafixSuite:
- remove unused OK (auto-classpath) *** FAILED *** (1 second, 39 milliseconds)
  java.nio.file.NoSuchFileException: .../scalafix-tests/expect/target/jvm-2.12.19-target2.12.19xsource3/test-classes.bak
```

By removing PathIO.workingDirectory from the --auto-classpath-roots, we
avoid side effects from other modules compilation, without weakening the
test that still targets many JARs with --auto-classpath-roots.