preserve no-op behavior when passing trees built with quasiquotes
Quasiquotes-generated trees have positions since scalameta#3450. Fixes:

error: patch.md:168:1: token not found:
Patch.removeImportee(importee"Future").showDiff()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
java.util.NoSuchElementException: token not found:
  at scalafix.util.TokenList.$anonfun$tok2idx$2(TokenList.scala:27)
  at scala.collection.immutable.Map$WithDefault.default(Map.scala:181)
  at scala.collection.MapOps.apply(Map.scala:176)
  at scala.collection.MapOps.apply$(Map.scala:175)
  at scala.collection.AbstractMap.apply(Map.scala:405)
  at scalafix.util.TokenList.leading(TokenList.scala:15)
  at scalafix.internal.patch.ImportPatchOps$.remove$1(ImportPatchOps.scala:229)