Added validation on the classpath
Address #962

This is a protection to avoid invalid entries from
creeping into the SymbolTable loading process. When this
happens, we get a pretty bad error that looks like:

`error: Unable to load symbol table: error in opening zip file`

This does not tell us much and we need to find the problematic
entry (if we can figure out what's the problem). With this PR,
an invalid we show up as an argument validation error either
via `run` or via the `validate` function on `Args`.

Before:

```
error: Unable to load symbol table: zip END header not found
1 targets failed
assignments.api.fix Unable to load symbol table: zip END header not found
```

After:

```
error: Invalid classpath entry. Make sure your classpath
contains only directories or file that ends with
the following extension: [jar,zip,semanticdb]. The following path are invalid: /some/path/to/a/file.json
```