Fix RedundantSyntax raw interpolator handling
RedundantSyntax raised an exception for some characters
were escaped in a raw interpolator.

scalafix.internal.v1.FileException: unexpected error processing file /workspace/A.scala
Caused by: scala.StringContext$InvalidEscapeException: invalid escape '\+' not one of [\b, \t, \n, \f, \r, \\, \", \', \uxxxx] at index 4 in "(.*)\+.*@(.*)". Use \\ for literal \.
at scala.StringContext$.loop$2(StringContext.scala:417)
at scala.StringContext$.replace(StringContext.scala:429)
at scala.StringContext$.processEscapes(StringContext.scala:387)
at scalafix.internal.rule.RedundantSyntax$$anonfun$fix$1.applyOrElse(RedundantSyntax.scala:39)